/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import model.Usuario;
import dao.UsuarioDAO;
import java.sql.ResultSet;
import javax.swing.JOptionPane;

/**
 *
 * @author Guilherme
 */
public class Login extends javax.swing.JFrame {

    /**
     * Creates new form Login
     */
    public Login() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        buttonSignIn = new java.awt.Button();
        buttonLoginCancel = new java.awt.Button();
        jLabelLoginUsuario = new javax.swing.JLabel();
        jLabelLoginSenha = new javax.swing.JLabel();
        jPasswordFieldLoginUsuarios = new javax.swing.JPasswordField();
        jTextFieldLoginUsuarios = new javax.swing.JTextField();
        jMenuBar2 = new javax.swing.JMenuBar();
        jMenuCobook = new javax.swing.JMenu();

        jMenuItem1.setText("jMenuItem1");

        jMenuItem2.setText("jMenuItem2");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("LoginPage");
        setResizable(false);

        buttonSignIn.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        buttonSignIn.setLabel("Sign In");
        buttonSignIn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonSignInActionPerformed(evt);
            }
        });

        buttonLoginCancel.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        buttonLoginCancel.setLabel("Cancel");
        buttonLoginCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonLoginCancelActionPerformed(evt);
            }
        });

        jLabelLoginUsuario.setBackground(new java.awt.Color(255, 0, 0));
        jLabelLoginUsuario.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        jLabelLoginUsuario.setText("Email");
        jLabelLoginUsuario.setPreferredSize(new java.awt.Dimension(40, 22));

        jLabelLoginSenha.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        jLabelLoginSenha.setText("Senha");
        jLabelLoginSenha.setPreferredSize(new java.awt.Dimension(40, 22));

        jPasswordFieldLoginUsuarios.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N

        jTextFieldLoginUsuarios.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N

        jMenuCobook.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-livros-64.png"))); // NOI18N
        jMenuCobook.setText("Cobook");
        jMenuCobook.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        jMenuBar2.add(jMenuCobook);

        setJMenuBar(jMenuBar2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(107, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabelLoginSenha, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jPasswordFieldLoginUsuarios, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabelLoginUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextFieldLoginUsuarios, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(151, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(buttonSignIn, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(121, 121, 121)
                        .addComponent(buttonLoginCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(180, 180, 180))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(83, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldLoginUsuarios, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelLoginUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(59, 59, 59)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelLoginSenha, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPasswordFieldLoginUsuarios, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(buttonSignIn, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonLoginCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(65, 65, 65))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void buttonSignInActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonSignInActionPerformed
        // TODO add your handling code here:
      
            String email = jTextFieldLoginUsuarios.getText();
            String senha = jPasswordFieldLoginUsuarios.getText();
        
            UsuarioDAO usuarioDAO = new UsuarioDAO();
            Usuario usuario = usuarioDAO.obter(email, senha);
                  
            if (usuario != null) {
                if (usuario.isAdministrador()) {
                    dispose();
                    TelaPrincipalAdm telaPrincipalAdm = new TelaPrincipalAdm(usuario);
                    telaPrincipalAdm.setVisible(true);
                } else {
                    dispose();
                    TelaPrincipalUsuarios telaPrincipalUsuarios = new TelaPrincipalUsuarios(usuario);
                    telaPrincipalUsuarios.setVisible(true); 
                }
            } else {
                JOptionPane.showMessageDialog(this, "Usuário e senha estão incorretos!");
                jTextFieldLoginUsuarios.setText("");
                jPasswordFieldLoginUsuarios.setText("");
            }
       
        
    }//GEN-LAST:event_buttonSignInActionPerformed

    private void buttonLoginCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonLoginCancelActionPerformed
        // TODO add your handling code here:
        jTextFieldLoginUsuarios.setText("");
        jPasswordFieldLoginUsuarios.setText("");
    }//GEN-LAST:event_buttonLoginCancelActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private java.awt.Button buttonLoginCancel;
    private java.awt.Button buttonSignIn;
    private javax.swing.JLabel jLabelLoginSenha;
    private javax.swing.JLabel jLabelLoginUsuario;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JMenu jMenuCobook;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JPasswordField jPasswordFieldLoginUsuarios;
    private javax.swing.JTextField jTextFieldLoginUsuarios;
    // End of variables declaration//GEN-END:variables
}
