/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import controller.LivroController;
import javax.swing.JOptionPane;
import model.Usuario;
import model.Livro;
/**
 *
 * @author Guilherme
 */
public class TelaCadastroLivros extends javax.swing.JFrame {
    Usuario usuario;
    /**
     * Creates new form TelaCadastroLivros
     */
    public TelaCadastroLivros(Usuario usuario) {
        this.usuario = usuario;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelCadastroLivros = new javax.swing.JPanel();
        jLabelTituloLivro = new javax.swing.JLabel();
        jTextFieldTituloLivro = new javax.swing.JTextField();
        jLabelTipoLivro = new javax.swing.JLabel();
        jTextFieldTipoLivro = new javax.swing.JTextField();
        jLabelAutorLivro = new javax.swing.JLabel();
        jTextFieldAutorLivro = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jButtonSalvarLivro = new javax.swing.JButton();
        jButtonLimparLivro = new javax.swing.JButton();
        jButtonCancelarLivro = new javax.swing.JButton();
        jFormattedTextFieldNotaLivro = new javax.swing.JFormattedTextField();
        jLabelCadastroLivros = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Livraria");
        setResizable(false);

        jPanelCadastroLivros.setBackground(new java.awt.Color(102, 102, 102));
        jPanelCadastroLivros.setPreferredSize(new java.awt.Dimension(780, 400));

        jLabelTituloLivro.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jLabelTituloLivro.setForeground(new java.awt.Color(255, 255, 255));
        jLabelTituloLivro.setText("Título:");

        jTextFieldTituloLivro.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N

        jLabelTipoLivro.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jLabelTipoLivro.setForeground(new java.awt.Color(255, 255, 255));
        jLabelTipoLivro.setText("Tipo:");

        jTextFieldTipoLivro.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N

        jLabelAutorLivro.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jLabelAutorLivro.setForeground(new java.awt.Color(255, 255, 255));
        jLabelAutorLivro.setText("Autor:");

        jTextFieldAutorLivro.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N

        jLabel1.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Nota:");

        jButtonSalvarLivro.setBackground(new java.awt.Color(240, 240, 240));
        jButtonSalvarLivro.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jButtonSalvarLivro.setText("Salvar");
        jButtonSalvarLivro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSalvarLivroActionPerformed(evt);
            }
        });

        jButtonLimparLivro.setBackground(new java.awt.Color(240, 240, 240));
        jButtonLimparLivro.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jButtonLimparLivro.setText("Limpar");
        jButtonLimparLivro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLimparLivroActionPerformed(evt);
            }
        });

        jButtonCancelarLivro.setBackground(new java.awt.Color(240, 240, 240));
        jButtonCancelarLivro.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jButtonCancelarLivro.setText("Cancelar");
        jButtonCancelarLivro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCancelarLivroActionPerformed(evt);
            }
        });

        jFormattedTextFieldNotaLivro.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("##"))));
        jFormattedTextFieldNotaLivro.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N

        javax.swing.GroupLayout jPanelCadastroLivrosLayout = new javax.swing.GroupLayout(jPanelCadastroLivros);
        jPanelCadastroLivros.setLayout(jPanelCadastroLivrosLayout);
        jPanelCadastroLivrosLayout.setHorizontalGroup(
            jPanelCadastroLivrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelCadastroLivrosLayout.createSequentialGroup()
                .addGroup(jPanelCadastroLivrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelCadastroLivrosLayout.createSequentialGroup()
                        .addGap(63, 63, 63)
                        .addGroup(jPanelCadastroLivrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelTituloLivro)
                            .addComponent(jLabelTipoLivro)
                            .addComponent(jLabelAutorLivro)
                            .addComponent(jLabel1))
                        .addGap(44, 44, 44)
                        .addGroup(jPanelCadastroLivrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTextFieldTituloLivro, javax.swing.GroupLayout.DEFAULT_SIZE, 490, Short.MAX_VALUE)
                            .addComponent(jTextFieldTipoLivro)
                            .addComponent(jTextFieldAutorLivro)
                            .addComponent(jFormattedTextFieldNotaLivro, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanelCadastroLivrosLayout.createSequentialGroup()
                        .addGap(114, 114, 114)
                        .addComponent(jButtonSalvarLivro)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonLimparLivro)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonCancelarLivro)))
                .addContainerGap(136, Short.MAX_VALUE))
        );
        jPanelCadastroLivrosLayout.setVerticalGroup(
            jPanelCadastroLivrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelCadastroLivrosLayout.createSequentialGroup()
                .addGap(58, 58, 58)
                .addGroup(jPanelCadastroLivrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelTituloLivro)
                    .addComponent(jTextFieldTituloLivro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanelCadastroLivrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelTipoLivro)
                    .addComponent(jTextFieldTipoLivro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanelCadastroLivrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelAutorLivro)
                    .addComponent(jTextFieldAutorLivro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanelCadastroLivrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jFormattedTextFieldNotaLivro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 93, Short.MAX_VALUE)
                .addGroup(jPanelCadastroLivrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonSalvarLivro)
                    .addComponent(jButtonLimparLivro)
                    .addComponent(jButtonCancelarLivro))
                .addGap(73, 73, 73))
        );

        jLabelCadastroLivros.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLabelCadastroLivros.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-livros-64.png"))); // NOI18N
        jLabelCadastroLivros.setText("Cadastro de Livros");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanelCadastroLivros, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(270, 270, 270)
                .addComponent(jLabelCadastroLivros)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jLabelCadastroLivros)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanelCadastroLivros, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(60, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonSalvarLivroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSalvarLivroActionPerformed
         boolean sucesso;
        double nota = Double.parseDouble(jFormattedTextFieldNotaLivro.getValue().toString());
        try {
            LivroController livroController = new LivroController();
            Livro livro = new Livro(jTextFieldTituloLivro.getText(),jTextFieldTipoLivro.getText(), jTextFieldAutorLivro.getText());
            sucesso = livroController.cadastrarLivro(this.usuario, livro, nota);
         if(sucesso){
             JOptionPane.showMessageDialog(null, "O cadastro foi realizado com sucesso!");
             this.jButtonLimparLivroActionPerformed(evt);
         } else {
             JOptionPane.showMessageDialog(null, "Os campos não foram preenchidos corretamente!");
         }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Erro:" + e);
        }
        
    }//GEN-LAST:event_jButtonSalvarLivroActionPerformed

    private void jButtonLimparLivroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLimparLivroActionPerformed
        jFormattedTextFieldNotaLivro.setText("");     
        jTextFieldTituloLivro.setText(""); 
        jTextFieldTipoLivro.setText(""); 
        jTextFieldAutorLivro.setText(""); 
    }//GEN-LAST:event_jButtonLimparLivroActionPerformed

    private void jButtonCancelarLivroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCancelarLivroActionPerformed
        dispose();
        if (usuario.isAdministrador()){
            TelaPrincipalAdm telaPrincipalAdm = new TelaPrincipalAdm(usuario);
            telaPrincipalAdm.setVisible(true);
        } else {
            TelaPrincipalUsuarios telaPrincipalUsuarios = new TelaPrincipalUsuarios(usuario);
            telaPrincipalUsuarios.setVisible(true); 
        }
    }//GEN-LAST:event_jButtonCancelarLivroActionPerformed

    /**
     * @param args the command line arguments
//     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(TelaCadastroLivros.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(TelaCadastroLivros.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(TelaCadastroLivros.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(TelaCadastroLivros.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new TelaCadastroLivros().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonCancelarLivro;
    private javax.swing.JButton jButtonLimparLivro;
    private javax.swing.JButton jButtonSalvarLivro;
    private javax.swing.JFormattedTextField jFormattedTextFieldNotaLivro;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabelAutorLivro;
    private javax.swing.JLabel jLabelCadastroLivros;
    private javax.swing.JLabel jLabelTipoLivro;
    private javax.swing.JLabel jLabelTituloLivro;
    private javax.swing.JPanel jPanelCadastroLivros;
    private javax.swing.JTextField jTextFieldAutorLivro;
    private javax.swing.JTextField jTextFieldTipoLivro;
    private javax.swing.JTextField jTextFieldTituloLivro;
    // End of variables declaration//GEN-END:variables
}
